version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Entered pre-build state
  build:
    commands:
      - echo Entered Build phase
      - mvn package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/**/*
    - .ebextensions/**/*
